### ISSUE TITLE
Configuration bat Got Wrong

### ISSUE THREAD

**Issue by Abel032** [Abel-8/opentoonz#2]
### Description

bat无法正确执行，有以下问题
1. 非管理员执行时（直接双击），无法添加reg
2. 管理员执行时，添加的reg键值是错误的

### Steps to Reproduce

0. 确保键被删除：HKEY_LOCAL_MACHINE\SOFTWARE\OpenToonz\OpenToonz
1. 双击bat
2. 管理员运行bat

### OpenToonz Version

Nightly (Specify below)

### Operating System

Windows 11

### GPU

NVIDIA

### Graphics Tablet

None

**Comment by Abel032** [comment]
@sorrowfoxmoil
![ad4f60cd76866b645acd191bf981136f](https://github.com/user-attachments/assets/6350138b-584e-4406-8fcc-5c19d49a7113)
![8947cd5600afb4778e0534455d52dc2b](https://github.com/user-attachments/assets/3a4ffba3-fb70-495c-9cb4-3ae8e73abf44)
![9e93fd6ed0033cb7f39cec2e1b9eb5f2](https://github.com/user-attachments/assets/45aaf957-da24-4540-b811-4da8e8ba1b53)

**Comment by sorrowfoxmoil** [comment]
### 这个问题看起来是匪夷所思的 
![屏幕截图 2024-11-30 113846](https://github.com/user-attachments/assets/acc9d550-379b-40e0-89bd-9d290f34829b)
当你的账户类型在控制面版的账户类型是“**管理员**”时，无论你要不要右键以管理员身份运行。这个bat都能正常添加stuff的键值
![管理员成功](https://github.com/user-attachments/assets/eaf38bf7-47f9-4e6f-8678-a67af7e4a376)

### 然而，如果你的账户类型在控制面版里的类型是“标准”
![image](https://github.com/user-attachments/assets/9638317f-162b-4649-a05a-998ee827a7f2)
![image](https://github.com/user-attachments/assets/57afdec6-c8f0-4fd1-b85c-4e1efcca6fae)
无论你是否以管理员身份运行这个bat，结果都是失败

![屏幕截图 2024-11-30 114039](https://github.com/user-attachments/assets/cf2953dc-b6e9-4c3a-93c5-ec71d6455850)

**Comment by Abel032** [comment]
如果bat文件仅仅用于生成reg文件的话，是否能规避cmd因为用户权限而添加失败的问题

**Comment by Abel032** [comment]
首先生成reg文件，完成后让系统打开reg

**Comment by Abel032** [comment]
同时，键值的错误无法复现吗

**Comment by sorrowfoxmoil** [comment]
无法复现键值错误的情况

**Comment by Abel032** [comment]
请上传标准用户使用管理员运行的截图

**Comment by sorrowmoil** [comment]
目前唯一能是bat正常工作的情况就是要在控制面板里将当前用户的“账户类型”设置为“管理员”

**Comment by Abel032** [comment]
有一种可能是，windows的标准用户使用管理员打开bat时并不更改所处文件夹的位置。

而CURRENT_PATH变量是通过cd命令获取的。

所以标准用户调用管理员权限运行bat，导致CURRENT_PATH变量变成了C:\Windows\System32\

为此，是否能更改获取CURRENT_PATH的方式？

> 目前唯一能是bat正常工作的情况就是要在控制面板里将当前用户的“账户类型”设置为“管理员”

**Comment by Abel032** [comment]
例如，在bat中先以标准用户的方式获取CURRENT_PATH，然后再向系统申请管理员权限，同时将CURRENT_PATH传递给新的具有管理员权限的cmd程序。

**Comment by sorrowmoil** [comment]
> 有一种可能是，windows的标准用户使用管理员打开bat时并不更改所处文件夹的位置。
> 
> 而CURRENT_PATH变量是通过cd命令获取的。
> 
> 所以标准用户调用管理员权限运行bat，导致CURRENT_PATH变量变成了C:\Windows\System32\
> 
> 为此，是否能更改获取CURRENT_PATH的方式？
> 
> > 目前唯一能是bat正常工作的情况就是要在控制面板里将当前用户的“账户类型”设置为“管理员”

而我刚才尝试了一下，在标准账户的前提下，就算你以管理员身份打开注册表，也无法在注册表里面建立新内容

**Comment by sorrowfoxmoil** [comment]
![非管理员身份 注册表不存在](https://github.com/user-attachments/assets/534b9c73-7a61-4e63-a0f6-74e0874ecda6)

**Comment by Abel-8** [comment]
能录屏吗

**Comment by Abel032** [comment]
由于windows不同版本的管理员权限有差异，建议生成reg文件然后调用windows系统打开reg文件

**Comment by Abel032** [comment]
首先只有管理员用户才能编辑注册表，非管理员用户可以不讨论

对于win11:
可能是因为win11的管理员用户，打开bat的角色并不是管理员，而是普通用户，导致Access deny
而用管理员权限打开bat又会改变当前所处目录，导致添加的路径错误

所以导致了问题的发生

**Comment by Abel032** [comment]
我认为生成reg文件然后使用regedit命令去打开reg文件是目前兼容性最好的方案。
